version: 2

before:
  hooks:
    - go -C src mod tidy
    - go -C src generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    dir: src
    ignore:
      - goos: linux
        goarch: arm64
      - goos: linux
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: dbee
    package_name: dbee
    homepage: https://github.com/murat-cileli/dbee
    description: |-
      Terminal based database browser.
    maintainer: Murat Cileli <murat.cileli@gmail.com>
    license: GNU GPL v3
    vendor: Murat Cileli
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    section: utils
    deb:
      fields:
        Bugs: https://github.com/murat-cileli/dbee/issues
    archlinux:
      packager: Murat Cileli <murat.cileli@gmail.com>

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
